name: Run tests

on:
  pull_request:
  push:
    branches: [main]

env:
  PROJECT_DIR: "."

jobs:
  tests:
    name: Run unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.19"

      - name: Install the project
        run: uv sync --extra test

      - name: Run tests
        run: uv run pytest tests